#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: MIT

# framework-agent installer (P2 PR-D).
#
# Idempotent. Standalone developer-pod setup; the inference_optimizer
# installer does not chain to it (framework-agent ships inside the
# hyperloom distribution).
# Targets a single Python venv (PEP 660 editable install) so the `fa`
# console script is on PATH alongside `inference_optimizer`.
#
# Env vars:
#   FRAMEWORK_AGENT_ROOT   default: this script's parent (computed below)
#   VENV_PYTHON            preferred Python interpreter. Auto-detects
#                          /opt/venv/bin/python on hyperloom/sgl-workspace
#                          containers (canonical ROCm stack). Set
#                          FRAMEWORK_AGENT_FORCE_PYTHON=1 to opt out of the
#                          auto-detect when VENV_PYTHON is explicitly set
#                          elsewhere.
#   PIP                    explicit override (ignored when VENV_PYTHON is set).
#                          Default: `pip` on PATH.
#   FRAMEWORK_AGENT_EXTRAS comma-separated extras to install; default 'ast,test'
#                          (libcst + patch-ng + pytest + jsonschema)
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
FRAMEWORK_AGENT_ROOT="${FRAMEWORK_AGENT_ROOT:-${PROJECT_ROOT}}"
KB_DIR="${FRAMEWORK_AGENT_KB_DIR:-${FRAMEWORK_AGENT_ROOT}/kb}"
EXTRAS="${FRAMEWORK_AGENT_EXTRAS:-ast,test}"

# Prefer /opt/venv/bin/python on hyperloom/sgl-workspace containers. The
# system /usr/bin/pip is too old (22.0.2 on Ubuntu 22.04) to honour the
# PEP 660 build_editable hook our pyproject declares, so editable install
# fails with "build backend is missing the 'build_editable' hook". Mirror
# src/hyperloom/inference_optimizer/assets/install.sh::resolve_python.
if [ -x "/opt/venv/bin/python" ] && [ "${FRAMEWORK_AGENT_FORCE_PYTHON:-0}" != "1" ]; then
    if [ -n "${VENV_PYTHON:-}" ] && [ "${VENV_PYTHON}" != "/opt/venv/bin/python" ]; then
        echo "[framework-agent/install.sh] preferring /opt/venv/bin/python over VENV_PYTHON=${VENV_PYTHON} (canonical ROCm stack)"
        echo "[framework-agent/install.sh]   set FRAMEWORK_AGENT_FORCE_PYTHON=1 to honour VENV_PYTHON verbatim"
    fi
    VENV_PYTHON="/opt/venv/bin/python"
fi

if [ -n "${VENV_PYTHON:-}" ] && [ -x "${VENV_PYTHON}" ]; then
    PIP="${VENV_PYTHON} -m pip"
elif [ -n "${PIP:-}" ]; then
    : # honour explicit override
else
    PIP="$(command -v pip || true)"
    if [ -z "${PIP}" ]; then
        echo "ERROR: install.sh: pip not found on PATH; set VENV_PYTHON or PIP." >&2
        exit 1
    fi
fi

echo "[framework-agent/install.sh] root=${FRAMEWORK_AGENT_ROOT}"
echo "[framework-agent/install.sh] extras=${EXTRAS}"
echo "[framework-agent/install.sh] pip=${PIP}"

# PEP 660 editable install. Idempotent -- re-running upgrades the wheel
# metadata in place but does not duplicate distributions.
${PIP} install -e "${PROJECT_ROOT}[${EXTRAS}]"

mkdir -p "${KB_DIR}"

# env.sh is consumed by inference_optimizer's _preflight() probe + by
# operators sourcing the env into an interactive shell.
#
# Self-resolves FRAMEWORK_AGENT_ROOT from BASH_SOURCE so the file is
# portable across users / clone paths. Avoid hard-coding absolute
# paths that bind env.sh to the developer machine where install.sh ran.
# KB_DIR is computed at install time so an override
# (FRAMEWORK_AGENT_KB_DIR) is preserved across re-sources.
_FA_PIP_BIN_DIR="$(dirname "${PIP%% *}")"
if [ "${KB_DIR}" = "${FRAMEWORK_AGENT_ROOT}/kb" ]; then
    _FA_KB_LINE='export FRAMEWORK_AGENT_KB_DIR="${FRAMEWORK_AGENT_ROOT}/kb"'
else
    _FA_KB_LINE="export FRAMEWORK_AGENT_KB_DIR=\"${KB_DIR}\""
fi
cat > "${SCRIPT_DIR}/env.sh" <<EOF
# Auto-generated by framework-agent/scripts/install.sh
# Do not hand-edit; rerun install.sh to regenerate.
_FA_SCRIPT_DIR="\$(cd "\$(dirname "\${BASH_SOURCE[0]:-\$0}")" && pwd)"
export FRAMEWORK_AGENT_ROOT="\$(cd "\${_FA_SCRIPT_DIR}/.." && pwd)"
${_FA_KB_LINE}
export PATH="${_FA_PIP_BIN_DIR}:\${PATH:-}"
unset _FA_SCRIPT_DIR
EOF
unset _FA_PIP_BIN_DIR _FA_KB_LINE

echo "[framework-agent/install.sh] OK -- 'fa --help' should resolve now."
