"""rocprofv3 --kernel-trace --stats wrapper and CSV parser.

Profiles an application and returns a ranked list of kernel execution stats.
Uses rocprofv3 with --kernel-trace --stats --output-format csv to collect
per-kernel aggregate statistics.
"""

import csv
import logging
import shutil
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

from kerncap._subprocess import run_streaming

logger = logging.getLogger(__name__)


@dataclass
class KernelStat:
    """Statistics for a single kernel from profiling."""

    name: str
    calls: int
    total_duration_ns: int
    avg_duration_ns: int
    percentage: float
    min_duration_ns: int = 0
    max_duration_ns: int = 0
    stddev_ns: float = 0.0


def run_profile(
    cmd: List[str],
    output_path: Optional[str] = None,
    rocprof_bin: Optional[str] = None,
    timeout: Optional[int] = None,
) -> List[KernelStat]:
    """Profile an application with rocprofv3 --kernel-trace --stats.

    Parameters
    ----------
    cmd : list[str]
        The application command to profile (e.g., ["./my_app", "--flag"]).
    output_path : str, optional
        Path to write the profile JSON summary.  If None, results are only
        returned in-memory.
    rocprof_bin : str, optional
        Path to rocprofv3 binary.  Auto-detected if None.
    timeout : int, optional
        Maximum seconds to wait for the application.  None means no limit.

    Returns
    -------
    list[KernelStat]
        Kernel statistics sorted by total duration (descending).
    """
    rocprof = rocprof_bin or shutil.which("rocprofv3")
    if not rocprof:
        raise FileNotFoundError(
            "rocprofv3 not found on PATH. Ensure ROCm is installed and "
            "source /opt/rocm/share/rocprofiler-sdk/setup-env.sh has been run."
        )

    with tempfile.TemporaryDirectory(prefix="kerncap_prof_") as tmpdir:
        full_cmd = [
            rocprof,
            "--kernel-trace",
            "--stats",
            "--output-format",
            "csv",
            "--output-directory",
            tmpdir,
            "--",
        ] + cmd

        try:
            proc = run_streaming(full_cmd, timeout=timeout)
        except subprocess.TimeoutExpired:
            raise TimeoutError(f"Application did not complete within {timeout}s")

        stats_csv = _find_stats_csv(tmpdir)

        if proc.returncode != 0 and not stats_csv:
            raise RuntimeError(
                f"rocprofv3 exited with code {proc.returncode}:\n"
                f"stdout: {proc.stdout}\n"
                f"stderr: {proc.stderr}"
            )

        if proc.returncode != 0:
            logger.warning(
                "rocprofv3 exited with code %d but produced output; continuing.",
                proc.returncode,
            )

        if not stats_csv:
            raise FileNotFoundError(
                f"rocprofv3 did not produce a kernel_stats.csv in "
                f"{tmpdir}. Files found: {_list_tree(tmpdir)}"
            )

        kernels = parse_kernel_trace_stats(stats_csv)

    if output_path:
        _write_profile_json(kernels, output_path, cmd)

    return kernels


def _find_stats_csv(base_dir: str) -> Optional[str]:
    """Locate the kernel stats CSV generated by rocprofv3.

    rocprofv3 outputs to <base_dir>/<hostname>/<pid>_kernel_stats.csv.
    We glob for the file since the hostname and pid are dynamic.
    """
    candidates = list(Path(base_dir).rglob("*kernel_stats.csv"))
    if candidates:
        return str(candidates[0])
    return None


def _list_tree(base_dir: str) -> List[str]:
    """Return a flat list of relative paths under base_dir for diagnostics."""
    return [str(p.relative_to(base_dir)) for p in Path(base_dir).rglob("*") if p.is_file()]


def parse_kernel_trace_stats(csv_path: str) -> List[KernelStat]:
    """Parse a rocprofv3 kernel_trace_stats.csv into KernelStat objects.

    Expected columns (rocprofv3 --kernel-trace --stats --output-format csv):
        "Name","Calls","TotalDurationNs","AverageNs","Percentage",
        "MinNs","MaxNs","StdDev"
    """
    with open(csv_path, "r") as f:
        lines = [line for line in f if not line.startswith("#")]

    if not lines:
        return []

    reader = csv.DictReader(lines)
    fieldnames = reader.fieldnames or []

    def _norm(s: str) -> str:
        return s.strip().strip('"').lower().replace(" ", "_")

    norm_map = {_norm(f): f for f in fieldnames}

    col_name = norm_map.get("name")
    col_calls = norm_map.get("calls")
    col_total = norm_map.get("totaldurationns")
    col_avg = norm_map.get("averagens")
    col_pct = norm_map.get("percentage")
    col_min = norm_map.get("minns")
    col_max = norm_map.get("maxns")
    col_stddev = norm_map.get("stddev")

    if not col_name:
        raise ValueError(f"Could not find kernel name column in {csv_path}. Columns: {fieldnames}")

    kernels = []
    for row in reader:
        name = row.get(col_name, "").strip().strip('"')
        if not name:
            continue

        calls = int(row.get(col_calls, 0)) if col_calls else 0
        total = int(row.get(col_total, 0)) if col_total else 0
        avg = int(float(row.get(col_avg, 0))) if col_avg else (total // calls if calls > 0 else 0)
        pct = float(row.get(col_pct, 0)) if col_pct else 0.0
        min_ns = int(row.get(col_min, 0)) if col_min else 0
        max_ns = int(row.get(col_max, 0)) if col_max else 0
        stddev = float(row.get(col_stddev, 0)) if col_stddev else 0.0

        kernels.append(
            KernelStat(
                name=name,
                calls=calls,
                total_duration_ns=total,
                avg_duration_ns=avg,
                percentage=pct,
                min_duration_ns=min_ns,
                max_duration_ns=max_ns,
                stddev_ns=stddev,
            )
        )

    kernels.sort(key=lambda k: k.total_duration_ns, reverse=True)
    return kernels


def _write_profile_json(kernels: List[KernelStat], path: str, cmd: List[str]) -> None:
    """Write profiling results as JSON."""
    import json
    import shlex
    from datetime import datetime, timezone

    data = {
        "cmd": shlex.join(cmd),
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "kernels": [
            {
                "name": k.name,
                "calls": k.calls,
                "total_duration_ns": k.total_duration_ns,
                "avg_duration_ns": k.avg_duration_ns,
                "percentage": k.percentage,
                "min_duration_ns": k.min_duration_ns,
                "max_duration_ns": k.max_duration_ns,
                "stddev_ns": k.stddev_ns,
            }
            for k in kernels
        ],
    }
    with open(path, "w") as f:
        json.dump(data, f, indent=2)
