// !!! This is a file automatically generated by hipify!!!
// Modified from https://github.com/CVMI-Lab/PAConv/tree/main/scene_seg/lib/pointops/src/knnquery_heap

#include <torch/serialize/tensor.h>
#include <torch/extension.h>
#include <vector>
#include <ATen/hip/HIPContext.h>

#define CHECK_CUDA(x) TORCH_CHECK(x.is_cuda(), #x, " must be a CUDAtensor ")
#define CHECK_CONTIGUOUS(x) TORCH_CHECK(x.is_contiguous(), #x, " must be contiguous ")
#define CHECK_INPUT(x) CHECK_CUDA(x);CHECK_CONTIGUOUS(x)


void knn_kernel_launcher(
    int b, int n, int m, int nsample,
    const float *xyz, const float *new_xyz,
    int *idx, float *dist2, hipStream_t stream);

void knn_kernel_launcher_opt(
    int b, int n, int m, int nsample, bool transposed,
    const float *xyz, const float *new_xyz,
    int *idx, hipStream_t stream);

// Legacy wrapper (backward compatible)
void knn_wrapper(int b, int n, int m, int nsample, at::Tensor xyz_tensor, at::Tensor new_xyz_tensor, at::Tensor idx_tensor, at::Tensor dist2_tensor)
{
    CHECK_INPUT(new_xyz_tensor);
    CHECK_INPUT(xyz_tensor);

    const float *new_xyz = new_xyz_tensor.data_ptr<float>();
    const float *xyz = xyz_tensor.data_ptr<float>();
    int *idx = idx_tensor.data_ptr<int>();
    float *dist2 = dist2_tensor.data_ptr<float>();

    hipStream_t stream = at::hip::getCurrentHIPStreamMasqueradingAsCUDA();

    knn_kernel_launcher(b, n, m, nsample, xyz, new_xyz, idx, dist2, stream);
}

// Optimized wrapper: no dist2, output is already (B, K, M), supports transposed input
void knn_wrapper_opt(int b, int n, int m, int nsample, bool transposed, at::Tensor xyz_tensor, at::Tensor new_xyz_tensor, at::Tensor idx_tensor)
{
    CHECK_CUDA(new_xyz_tensor);
    CHECK_CUDA(xyz_tensor);

    const float *new_xyz = new_xyz_tensor.data_ptr<float>();
    const float *xyz = xyz_tensor.data_ptr<float>();
    int *idx = idx_tensor.data_ptr<int>();

    hipStream_t stream = at::hip::getCurrentHIPStreamMasqueradingAsCUDA();

    knn_kernel_launcher_opt(b, n, m, nsample, transposed, xyz, new_xyz, idx, stream);
}


PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("knn_wrapper", &knn_wrapper, "knn_wrapper");
    m.def("knn_wrapper_opt", &knn_wrapper_opt, "knn_wrapper_opt");
}
