###############################################################################
# Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.
#
# See LICENSE for license information.
###############################################################################

#!/usr/bin/env python3
"""Generate TraceLens/PerfModel/_known_aten_ops.py from the current PyTorch installation.

Collects all op names from torch.ops.* namespaces (e.g. aten, prims) and
torch.distributed, then writes them as a Python set. This vendored set is
used by _parse_kernel_name() in triton_compiled_perf_model.py to segment
fused op names in Triton kernels without requiring torch at analysis time.

Run this script on a developer machine whenever the target PyTorch version
is bumped, then commit the updated file.

Usage:
    python scripts/generate_known_aten_ops.py
"""

import logging
import os
import textwrap

import torch

logger = logging.getLogger(__name__)

ops: set[str] = set()

for ns_name in dir(torch.ops):
    if ns_name.startswith("__"):
        continue
    try:
        ns = getattr(torch.ops, ns_name)
        ops.update(n for n in dir(ns) if not n.startswith("__"))
    except Exception:
        logger.debug("Skipping torch.ops namespace %s", ns_name, exc_info=True)

if hasattr(torch, "distributed"):
    ops.update(n for n in dir(torch.distributed) if not n.startswith("_") and "_" in n)

out_path = os.path.normpath(
    os.path.join(
        os.path.dirname(__file__), "..", "TraceLens", "PerfModel", "_known_aten_ops.py"
    )
)

items = ", ".join(f'"{op}"' for op in sorted(ops))
content = textwrap.dedent(f"""\
    ###############################################################################
    # Copyright (c) 2025 Advanced Micro Devices, Inc. All rights reserved.
    #
    # See LICENSE for license information.
    ###############################################################################

    # Auto-generated by scripts/generate_known_aten_ops.py (torch {torch.__version__}).
    # Do not edit manually. Re-run the script when the target PyTorch version is bumped.
    KNOWN_OPS = {{{items}}}
""")

with open(out_path, "w") as f:
    f.write(content)

print(f"Wrote {len(ops)} ops to {out_path} (torch {torch.__version__})")
